# After creating the secret use the following to set the data with your custom docker config json.
# oc set data secret/pull-secret --from-file=.dockerconfigjson=/home/vince/.docker/config.json -n ztp-spoke-01
# or
# oc create secret docker-registry --from-file=.dockerconfigjson=/home/vince/.docker/config.json pull-secret -n ztp-spoke-01

apiVersion: v1
data:
  .dockerconfigjson: <redacted>
kind: Secret
metadata:
  name: pull-secret
  namespace: ztp-spoke-01
