apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: ztp-cluster-01
  namespace: ztp-cluster-01
spec:
  baseDomain: lab.local
  clusterName: ztp-cluster-01
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: ztp-cluster-01
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "ztp-cluster-01"
  pullSecretRef:
    name: pull-secret
