apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ztp-cluster-01
  namespace: ztp-cluster-01
  labels:
    name: ztp-cluster-01
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
