apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  mirrorRegistryRef:
    name: assisted-installer-mirror-config
  osImages:
    - openshiftVersion: "4.14"
      cpuArchitecture: "x86_64"
      version: "414.92.202407091253-0"
      url: "http://192.168.1.72/rhcos/rhcos-4.14.34-x86_64-live.x86_64.iso"
      rootFSUrl: "http://192.168.1.72/rhcos/rhcos-4.14.34-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.15"
      cpuArchitecture: "x86_64"
      version: "415.92.202407091355-0"
      url: "http://192.168.1.72/rhcos/rhcos-4.15.23-x86_64-live.x86_64.iso"
      rootFSUrl: "http://192.168.1.72/rhcos/rhcos-4.15.23-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.16"
      cpuArchitecture: "x86_64"
      version: "416.94.202406251923-0"
      url: "http://192.168.1.72/rhcos/rhcos-4.16.3-x86_64-live.x86_64.iso"
      rootFSUrl: "http://192.168.1.72/rhcos/rhcos-4.16.3-x86_64-live-rootfs.x86_64.img"
