apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  labels:
    cluster-name: ztp-cluster-02
  name: ztp-cluster-02
  namespace: ztp-cluster-02
spec:
  clusterDeploymentRef:
    name: ztp-cluster-02
  imageSetRef:
    name: img4.16.8-x86-64-appsub
  networking:
    networkType: OVNKubernetes
    userManagedNetworking: true
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.132.0/24
    serviceNetwork:
      - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 1
    workerAgents: 0
  sshPublicKey: <redactec>
