apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ztp-cluster-02
  namespace: ztp-cluster-02
spec:
  applicationManager:
    argocdCluster: false
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    name: ztp-cluster-02
    cloud: Baremetal
    vendor: auto-detect
  clusterName: ztp-cluster-02
  clusterNamespace: ztp-cluster-02
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
