apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ztp-spoke-02
  namespace: ztp-spoke-02
spec:
  applicationManager:
    argocdCluster: false
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    name: ztp-spoke-02
    cloud: Baremetal
    vendor: auto-detect
  clusterName: ztp-spoke-02
  clusterNamespace: ztp-spoke-02
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
