apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ztp-spoke-02
  namespace: ztp-spoke-02
  labels:
    name: ztp-spoke-02
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
